steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/s-inventory/docker-repo/s-inventory-p",
        "-f",
        "Dockerfile.prod",
        "--platform=linux/amd64",
        "--build-arg",
        "DB_DIALECT=$(cat .env.prod | grep DB_DIALECT | cut -d '=' -f2)",
        "--build-arg",
        "PORT=$(cat .env.prod | grep PORT | cut -d '=' -f2)",
        "--build-arg",
        "DB_URL=$(cat .env.prod | grep DB_URL | cut -d '=' -f2)",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/s-inventory/docker-repo/s-inventory-p",
      ]
options:
  logging: CLOUD_LOGGING_ONLY