services:
  s-inventory:
    image: s-inventory-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - PORT=${PORT}
        - DB_DIALECT=${DB_DIALECT}
        - DB_URL=${DB_URL}
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DB_DIALECT=${DB_DIALECT}
      - DB_URL=${DB_URL}
