services:
  s-inventory:
    image: us-central1-docker.pkg.dev/s-inventory/docker-repo/s-inventory-p
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - PORT=${PORT}
        - DB_DIALECT=${DB_DIALECT}
        - DB_URL=${DB_URL}
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DB_DIALECT=${DB_DIALECT}
      - DB_URL=${DB_URL}
