services:
  s-inventory:
    image: s-inventory-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    environment:
      - DB_DIALECT=${DB_DIALECT}
      - DB_URL=${DB_URL}
