# =============
# dependecies
# =============
FROM node:21-alpine3.19 AS deps

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i

# =============
# builder
# =============
FROM node:21-alpine3.19 AS build

ARG DB_DIALECT
ENV DB_DIALECT=$DB_DIALECT

ARG PORT
ENV PORT=$PORT

ARG DB_URL
ENV DB_URL=$DB_URL

WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . ./

RUN npm run build
RUN npm ci -f --only=production && npm cache clean --force

RUN npm run m:run:prod

# =============
# runner
# =============
FROM node:21-alpine3.19 AS prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules

ENV NODE_ENV=production

USER node

EXPOSE 3001

CMD [ "node", "dist/main.js" ]
